id: 1dac516a-291d-416d-b8ca-aed61f2062df

slug: ado-dotnet
description: |
  ## Comprehensive monitoring quickstart for ADO.NET

  When you monitor ADO.NET with New Relic, you can observe your ADO.NET data set in real time. Our .NET agent will also let you correlate transactions moving across your application environment and troubleshoot while working in a live development environment.


  ## Why monitor ADO.NET?

  Discovering data access API calls can help in identifying the following issues:
    - Inaccessible databases or issues with the network library.
    - Database and client software schema incompatibility.
    - Problems occur when different ADO.NET components interact with one another or your own components.
    - Whether hard-coded or created by an application, incorrect SQL.
    - Flawed programming logic.

  ## What’s included in this quickstart?

  The ADO.NET monitoring quickstart from New Relic provides immediate full-stack observability:
    - Alerts (high load connection, hard connects exceeding max limit, pool size exceeding optimum limit).
    - Dashboards (hard connects per second, hard disconnects per second, number of active connections, soft connects per second and more).
    - Alerts inform end users about the quality of their applications on a proactive basis.
    - Monitor web transactions.


summary: |
  Discover how the ADO.NET quickstart gives you an advantage with comprehensive monitoring capabilities.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: ADO.NET
documentation:
  - name: ADO.NET installation docs
    description: |
      Open-source web application framework developed by Microsoft, which
      implements the model-view-controller pattern.
    url: >- 
      https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework#technologies
keywords:
  - apm
  - dotnet
  - .net
  - ado.net
  - ado-dotnet
installPlans:
  - dotnet-agent

dashboards:
  - ado-dotnet
alertPolicies:
  - ado-dotnet
