id: third-party-jenkins-prometheus
name: Jenkins (Prometheus)
title: Jenkins (Prometheus) 
description: |
  Jenkins is open source automation server, Jenkins provides hundreds of plugins to support building, deploying and automating any project.

target:
  type: integration
  destination: cloud

install:
  mode: link
  destination:
    url: https://plugins.jenkins.io/prometheus/