id: 235cda5f-f9e6-4c81-b1d2-55fc80717a06
# Sets the URL name of the quickstart on public I/O (required)
slug: ext-influxdb

# Displayed in the UI (required)
title: InfluxDB

# Long-form description of the quickstart (required)
description: |
  The InfluxDB quickstart allows you to get visibility into the performance and available of your InfluxDB service and dependencies. Use this quickstart together with the mock up integrations.

  # InfluxDB quickstart highlights

  The New Relic quickstart uses dashboards to proactively monitor your InfluxDB servers, like;
  - number of query requests
  - task execution failures
  - memory (cache/heap)
  
  ## Monitoring InfluxDB

  This quickstart utilizes New Relic's ability to ingest Prometheus data (either from our OpenMetrics integration or via Prometheus remote write). See instructions for [sending Prometheus data to New Relic here](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/).

  ### How do I configure my integration to scrape InfluxDB severs?

  The approach to getting your Prometheus metrics into New Relic differs depending on which integration you use.

  #### Prometheus Remote Write

  In addition to setting up your `remote_write` configuration as described [here](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/), you will need to add the following scrape configuration to your `prometheus.yml` config file

  ```
  - job_name: 'influxdb'
    metrics_path: "/metrics"
    scheme: http
    static_configs:
    - targets: ['your_influxdb_server_here:8086']
  ```
  Prometheus job definition sourced from [InfluxDB - Prometheus](https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/#prometheus-remote-read-and-write-api-support)

  Use this link to check that your InfluxDB services are appearing under your [Prometheus targets](https://prometheus.io/docs/prometheus/latest/querying/api/#targets).

  ##### Integrating your Prometheus Data 
  Using the Prometheus Remote Write integration, you can point your Prometheus servers at New Relic to store and visualize your data.
  
  - Generate your Prometheus remote_write URL
  - Use 'InfluxDB_Prometheus' to identify your data source
  - This will add an attribute to your metrics that will enable the entity creation - *instrumentation.source = "InfluxDB_Prometheus"*

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  The InfluxDB quickstart allows you to get visibility into the performance of your instances.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - David Perez @Kinect-Consulting
  - Omar Castillo @Kinect-Consulting
  - Irvin Arias @Kinect-Consulting

# Keywords for filtering / searching criteria in the UI
keywords:
  - InfluxData
  - InfluxDB
  - Database
  - Timeseries

# Reference to install plans located under /install directory
installPlans:
  - ext-influxdb
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
alertPolicies:
  - ext-influxdb
dashboards:
  - ext-influxdb
  
# Content / Design
icon: logo.png
website: https://www.influxdata.com/
